Switch to CMake. (#418)
* Try using CMake.

* Avoid error: ‘exchange’ is not a member of ‘std’

* Add missing Alpine support.

* Add missing C flags for FFTW.

* Add absolute paths when compiling fftw3.

* Only target C code with FFTW flags.

* Don't just ignore juce_patched_gui_basics.cpp on APPLE.

* Add missing gettimeofday import.

* runner.workspace => github.workspace, also don't try to load a kernel ext

* No more Python 3.8, and also -latomic.

* Don't test PulseAudio dummy input.

* Move Ruff config to pyproject.toml.

* Add includetime.h for musl.

* Do we need HAVE_SYS_TIME_H?

* Does this fix Win32?

* More iterative test fixing...

* Comment out failing Windows builds.

* Skip more devices.

* Try to fix Windows build by adding more to CMakeLists.

* Why can't we find python312.lib?

* Is disabling build isolation on Windows all it takes?

* This Windows build will be the death of me.

* Time for way more debug output.

* Why do I have to set these manually?

* If you leave a trailing comma in the OS name, the action won't start.

* Windows, oh Windows.

* Just focus on Windows.

* Debug info, more and more debug info.

* Manually pull in Python_LIBRARY if necessary.

* Clean this up a bit. It does compile, though!

* D'oh.

* Re-enable build matrix.

* ...but not on 3.8.

* macos-12 is gone

* Move cibuildwheel flags to pyproject.toml.

* Whoops, test-command, not test.

* ...and this one too.